on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: select compatible xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
