name: Submit Dependency Snapshot

on:
  pull_request:
    branches: [main]
#     paths:
#       - "Packages/*.pkl"

env:
  PKL_VERSION: 0.26.3
  PKL_ARCH: macos-aarch64
#   GITHUB_API_URL: https://api.github.com/repos/willswire/cosmic/dependency-graph/snapshots

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install pkl
        run: |
          curl -L -o pkl "https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-${PKL_ARCH}"
          chmod +x pkl
          sudo mv pkl /usr/local/bin/pkl
          pkl --version

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies
        run: npm ci --prefix .github/workflows/dependency-submission/

      - name: Run all NPM build/test actions
        run: npm run all --prefix .github/workflows/dependency-submission/

      - name: Run dependency submission
        uses: ./.github/workflows/dependency-submission/
      # jobs:
      #   submit-dependencies:
      #     runs-on: macos-14
      #     steps:
      #       - uses: actions/checkout@v4

      #       - name: Install pkl
      #         run: |
      #           curl -L -o pkl "https://github.com/apple/pkl/releases/download/${PKL_VERSION}/pkl-${PKL_ARCH}"
      #           chmod +x pkl
      #           sudo mv pkl /usr/local/bin/pkl
      #           pkl --version

      #       - name: Evaluate PKL files
      #         id: eval-pkl
      #         run: |
      #           for FILE in $(find Packages -type f -name '*.pkl' ! -name '.*'); do
      #             pkl eval -f json $FILE > Packages/$(basename ${FILE%.pkl}.json)
      #           done

      #       - name: Submit Dependency Snapshot to GitHub
      #         run: |
      #           sha=$(git rev-parse HEAD)
      #           timestamp=$(date +'%Y-%m-%dT%H:%M:%SZ')

      #           for JSON_FILE in $(find Packages -type f -name '*.json'); do
      #             curl -L \
      #               -X POST \
      #               -H "Accept: application/vnd.github+json" \
      #               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #               -H "X-GitHub-Api-Version: 2022-11-28" \
      #               $GITHUB_API_URL \
      #               -d "{
      #                 \"version\": 0,
      #                 \"sha\": \"${sha}\",
      #                 \"ref\": \"refs/heads/main\",
      #                 \"job\": {
      #                   \"correlator\": \"submit-dependencies\",
      #                   \"id\": \"${{ github.run_id }}\"
      #                 },
      #                 \"detector\": {
      #                   \"name\": \"pkl-detector\",
      #                   \"version\": \"${PKL_VERSION}\",
      #                   \"url\": \"https://github.com/apple/pkl\"
      #                 },
      #                 \"scanned\": \"${timestamp}\",
      #                 \"manifests\": {
      #                   \"$(basename $JSON_FILE)\": {
      #                     \"name\": \"$(basename $JSON_FILE)\",
      #                     \"file\": {
      #                       \"source_location\": \"$JSON_FILE\"
      #                     }
      #                   }
      #                 }
      #               }"
      #           done

      - uses: actions/checkout@v3

      - uses: advanced-security/sbom-generator-action@v0.0.1
        id: sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3.1.0
        with:
          path: ${{steps.sbom.outputs.fileName }}
          name: "SBOM"
