name: Lint

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main]

jobs:
  lint:
    name: SwiftLint Linting
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: |
          brew install swiftlint
          swiftlint version

      - name: Run SwiftLint
        run: swiftlint
