on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install pkl
        run: brew install pkl
      - uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Cosmic-*/SourcePackages/
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          save-always: true
      - name: Execute build
        run: xcodebuild build -scheme "$SCHEME" -destination "$DESTINATION" CODE_SIGNING_ALLOWED='NO' | xcpretty && exit ${PIPESTATUS[0]}
        env:
          DESTINATION: platform=macOS,arch=arm64
          SCHEME: Cosmic
      - name: Execute test
        run: xcodebuild test -resultBundlePath TestResults -scheme "$SCHEME" -destination "$DESTINATION" CODE_SIGNING_ALLOWED='NO' | xcpretty && exit ${PIPESTATUS[0]}
        env:
          DESTINATION: platform=macOS,arch=arm64
          SCHEME: CosmicTests
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults.xcresult/
        if: success() || failure()
      # - uses: kishikawakatsumi/xcresulttool@v1
      #   with:
      #     path: TestResults.xcresult
      #   if: success() || failure()
