on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: select xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: execute test
        run: xcodebuild test -resultBundlePath TestResults -scheme "$SCHEME" -destination "$DESTINATION" CODE_SIGNING_ALLOWED='NO'
        env:
          DESTINATION: platform=macOS,arch=arm64
          SCHEME: CosmicTests
      - uses: willswire/xcresulttool@main
        with:
          path: TestResults.xcresult
        if: success() || failure()
